packages:
  - "apps/*"
  - "packages/*"

catalog:
  # React
  react: ^19.0.0
  react-dom: ^19.0.0
  "@types/react": ^19.0.0
  "@types/react-dom": ^19.0.0

  # Next.js
  next: ^15.0.0
  eslint-config-next: ^15.0.0
  "@next/eslint-plugin-next": ^15.0.0

  # TypeScript
  typescript: ^5.3.3

  # Styling
  tailwindcss: ^4.0.0
  postcss: ^8.4.33
  autoprefixer: ^10.4.17
  "@tailwindcss/postcss": ^4.1.15
  clsx: ^2.1.0
  tailwind-merge: ^2.2.1
  class-variance-authority: ^0.7.0
  lucide-react: ^0.554.0

  # Linting
  eslint: ^9.39.1
  eslint-config-prettier: ^9.1.0
  "@eslint/eslintrc": ^3.2.0
  "@typescript-eslint/eslint-plugin": ^8.0.0
  "@typescript-eslint/parser": ^8.0.0

  # Build/Test
  tsup: ^8.0.1
  vite: ^7.2.2
  vitest: ^4.0.10
  "@vitejs/plugin-react": ^4.2.1
  jsdom: ^24.0.0
  "@testing-library/react": ^15.0.0
  "@testing-library/jest-dom": ^6.5.0

  # Storybook
  storybook: ^10.0.0
  "@storybook/addon-links": ^10.0.0
  "@storybook/react": ^10.0.0
  "@storybook/nextjs-vite": ^10.0.0
  "@storybook/react-vite": ^10.0.0
