packages:
  - "apps/*"
  - "packages/*"

catalog:
  storybook: ^10.0.0
  "@storybook/addon-links": ^10.0.0
  "@storybook/react": ^10.0.0
  "@storybook/nextjs-vite": ^10.0.0
  "@storybook/react-vite": ^10.0.0
